
POST http://localhost:8080/posts/
content-type: application/json

{
  "title": "React On Page Scroll Progress Bar with Web",
  "body": "Do you want to display a progress bar on page scroll in React application? Well, then you are at the right place. We are going to build a progress bar only using pure JavaScript and CSS in a React 16+ application.",
  "author": "tom"
}

###

GET http://localhost:8080/posts/
###

PATCH  http://localhost:8080/posts/5f49001fca36fb004218bf5e
content-type: application/json

{
  "title": "New title2",
  "body": "Lorem ipsum"
}
###

DELETE http://localhost:8080/posts/5f4905ce25399400df1427ae




// register

###
POST http://localhost:8080/register
content-type: application/json

{
  "name": "Jedai",
  "lastName": "Skywalker",
  "email": "luck@star0.com",
  "password": "darkwader",
  "role": 0
}
//login form
################################################################

POST http://localhost:8080/login
content-type: application/json

{
   "email": "luck@star0.com",
  "password": "darkwader"
}

###